[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#095B25"
backgroundColor = "#F4F7F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"
